export const countryList = {
  "AFG": { "code3": "AFG", "name": "Afghanistan", "number": "004"},
  "ALB": { "code3": "ALB", "name": "Albania", "number": "008"},
  "DZA": { "code3": "DZA", "name": "Algeria", "number": "012"},
  "ASM": { "code3": "ASM", "name": "American Samoa", "number": "016"},
  "AND": { "code3": "AND", "name": "Andorra", "number": "020"},
  "AGO": { "code3": "AGO", "name": "Angola", "number": "024"},
  "AIA": { "code3": "AIA", "name": "Anguilla", "number": "660"},
  "ATA": { "code3": "ATA", "name": "Antarctica", "number": "010"},
  "ATG": { "code3": "ATG", "name": "Antigua and Barbuda", "number": "028"},
  "ARG": { "code3": "ARG", "name": "Argentina", "number": "032"},
  "ARM": { "code3": "ARM", "name": "Armenia", "number": "051"},
  "ABW": { "code3": "ABW", "name": "Aruba", "number": "533"},
  "AUS": { "code3": "AUS", "name": "Australia", "number": "036"},
  "AUT": { "code3": "AUT", "name": "Austria", "number": "040"},
  "AZE": { "code3": "AZE", "name": "Azerbaijan", "number": "031"},
  "BHS": { "code3": "BHS", "name": "Bahamas (the)", "number": "044"},
  "BHR": { "code3": "BHR", "name": "Bahrain", "number": "048"},
  "BGD": { "code3": "BGD", "name": "Bangladesh", "number": "050"},
  "BRB": { "code3": "BRB", "name": "Barbados", "number": "052"},
  "BLR": { "code3": "BLR", "name": "Belarus", "number": "112"},
  "BEL": { "code3": "BEL", "name": "Belgium", "number": "056"},
  "BLZ": { "code3": "BLZ", "name": "Belize", "number": "084"},
  "BEN": { "code3": "BEN", "name": "Benin", "number": "204"},
  "BMU": { "code3": "BMU", "name": "Bermuda", "number": "060"},
  "BTN": { "code3": "BTN", "name": "Bhutan", "number": "064"},
  "BOL": { "code3": "BOL", "name": "Bolivia (Plurinational State of)", "number": "068"},
  "BES": { "code3": "BES", "name": "Bonaire, Sint Eustatius and Saba", "number": "535"},
  "BIH": { "code3": "BIH", "name": "Bosnia and Herzegovina", "number": "070"},
  "BWA": { "code3": "BWA", "name": "Botswana", "number": "072"},
  "BVT": { "code3": "BVT", "name": "Bouvet Island", "number": "074"},
  "BRA": { "code3": "BRA", "name": "Brazil", "number": "076"},
  "IOT": { "code3": "IOT", "name": "British Indian Ocean Territory (the)", "number": "086"},
  "BRN": { "code3": "BRN", "name": "Brunei Darussalam", "number": "096"},
  "BGR": { "code3": "BGR", "name": "Bulgaria", "number": "100"},
  "BFA": { "code3": "BFA", "name": "Burkina Faso", "number": "854"},
  "BDI": { "code3": "BDI", "name": "Burundi", "number": "108"},
  "CPV": { "code3": "CPV", "name": "Cabo Verde", "number": "132"},
  "KHM": { "code3": "KHM", "name": "Cambodia", "number": "116"},
  "CMR": { "code3": "CMR", "name": "Cameroon", "number": "120"},
  "CAN": { "code3": "CAN", "name": "Canada", "number": "124"},
  "CYM": { "code3": "CYM", "name": "Cayman Islands (the)", "number": "136"},
  "CAF": { "code3": "CAF", "name": "Central African Republic (the)", "number": "140"},
  "TCD": { "code3": "TCD", "name": "Chad", "number": "148"},
  "CHL": { "code3": "CHL", "name": "Chile", "number": "152"},
  "CHN": { "code3": "CHN", "name": "China", "number": "156"},
  "CXR": { "code3": "CXR", "name": "Christmas Island", "number": "162"},
  "CCK": { "code3": "CCK", "name": "Cocos (Keeling) Islands (the)", "number": "166"},
  "COL": { "code3": "COL", "name": "Colombia", "number": "170"},
  "COM": { "code3": "COM", "name": "Comoros (the)", "number": "174"},
  "COD": { "code3": "COD", "name": "Congo (the Democratic Republic of the)", "number": "180"},
  "COG": { "code3": "COG", "name": "Congo (the)", "number": "178"},
  "COK": { "code3": "COK", "name": "Cook Islands (the)", "number": "184"},
  "CRI": { "code3": "CRI", "name": "Costa Rica", "number": "188"},
  "HRV": { "code3": "HRV", "name": "Croatia", "number": "191"},
  "CUB": { "code3": "CUB", "name": "Cuba", "number": "192"},
  "CUW": { "code3": "CUW", "name": "Curaçao", "number": "531"},
  "CYP": { "code3": "CYP", "name": "Cyprus", "number": "196"},
  "CZE": { "code3": "CZE", "name": "Czechia", "number": "203"},
  "CIV": { "code3": "CIV", "name": "Côte d'Ivoire", "number": "384"},
  "DNK": { "code3": "DNK", "name": "Denmark", "number": "208"},
  "DJI": { "code3": "DJI", "name": "Djibouti", "number": "262"},
  "DMA": { "code3": "DMA", "name": "Dominica", "number": "212"},
  "DOM": { "code3": "DOM", "name": "Dominican Republic (the)", "number": "214"},
  "ECU": { "code3": "ECU", "name": "Ecuador", "number": "218"},
  "EGY": { "code3": "EGY", "name": "Egypt", "number": "818"},
  "SLV": { "code3": "SLV", "name": "El Salvador", "number": "222"},
  "GNQ": { "code3": "GNQ", "name": "Equatorial Guinea", "number": "226"},
  "ERI": { "code3": "ERI", "name": "Eritrea", "number": "232"},
  "EST": { "code3": "EST", "name": "Estonia", "number": "233"},
  "SWZ": { "code3": "SWZ", "name": "Eswatini", "number": "748"},
  "ETH": { "code3": "ETH", "name": "Ethiopia", "number": "231"},
  "FLK": { "code3": "FLK", "name": "Falkland Islands (the) [Malvinas]", "number": "238"},
  "FRO": { "code3": "FRO", "name": "Faroe Islands (the)", "number": "234"},
  "FJI": { "code3": "FJI", "name": "Fiji", "number": "242"},
  "FIN": { "code3": "FIN", "name": "Finland", "number": "246"},
  "FRA": { "code3": "FRA", "name": "France", "number": "250"},
  "GUF": { "code3": "GUF", "name": "French Guiana", "number": "254"},
  "PYF": { "code3": "PYF", "name": "French Polynesia", "number": "258"},
  "ATF": { "code3": "ATF", "name": "French Southern Territories (the)", "number": "260"},
  "GAB": { "code3": "GAB", "name": "Gabon", "number": "266"},
  "GMB": { "code3": "GMB", "name": "Gambia (the)", "number": "270"},
  "GEO": { "code3": "GEO", "name": "Georgia", "number": "268"},
  "DEU": { "code3": "DEU", "name": "Germany", "number": "276"},
  "GHA": { "code3": "GHA", "name": "Ghana", "number": "288"},
  "GIB": { "code3": "GIB", "name": "Gibraltar", "number": "292"},
  "GRC": { "code3": "GRC", "name": "Greece", "number": "300"},
  "GRL": { "code3": "GRL", "name": "Greenland", "number": "304"},
  "GRD": { "code3": "GRD", "name": "Grenada", "number": "308"},
  "GLP": { "code3": "GLP", "name": "Guadeloupe", "number": "312"},
  "GUM": { "code3": "GUM", "name": "Guam", "number": "316"},
  "GTM": { "code3": "GTM", "name": "Guatemala", "number": "320"},
  "GGY": { "code3": "GGY", "name": "Guernsey", "number": "831"},
  "GIN": { "code3": "GIN", "name": "Guinea", "number": "324"},
  "GNB": { "code3": "GNB", "name": "Guinea-Bissau", "number": "624"},
  "GUY": { "code3": "GUY", "name": "Guyana", "number": "328"},
  "HTI": { "code3": "HTI", "name": "Haiti", "number": "332"},
  "HMD": { "code3": "HMD", "name": "Heard Island and McDonald Islands", "number": "334"},
  "VAT": { "code3": "VAT", "name": "Holy See (the)", "number": "336"},
  "HND": { "code3": "HND", "name": "Honduras", "number": "340"},
  "HKG": { "code3": "HKG", "name": "Hong Kong", "number": "344"},
  "HUN": { "code3": "HUN", "name": "Hungary", "number": "348"},
  "ISL": { "code3": "ISL", "name": "Iceland", "number": "352"},
  "IND": { "code3": "IND", "name": "India", "number": "356"},
  "IDN": { "code3": "IDN", "name": "Indonesia", "number": "360"},
  "IRN": { "code3": "IRN", "name": "Iran (Islamic Republic of)", "number": "364"},
  "IRQ": { "code3": "IRQ", "name": "Iraq", "number": "368"},
  "IRL": { "code3": "IRL", "name": "Ireland", "number": "372"},
  "IMN": { "code3": "IMN", "name": "Isle of Man", "number": "833"},
  "ISR": { "code3": "ISR", "name": "Israel", "number": "376"},
  "ITA": { "code3": "ITA", "name": "Italy", "number": "380"},
  "JAM": { "code3": "JAM", "name": "Jamaica", "number": "388"},
  "JPN": { "code3": "JPN", "name": "Japan", "number": "392"},
  "JEY": { "code3": "JEY", "name": "Jersey", "number": "832"},
  "JOR": { "code3": "JOR", "name": "Jordan", "number": "400"},
  "KAZ": { "code3": "KAZ", "name": "Kazakhstan", "number": "398"},
  "KEN": { "code3": "KEN", "name": "Kenya", "number": "404"},
  "KIR": { "code3": "KIR", "name": "Kiribati", "number": "296"},
  "PRK": { "code3": "PRK", "name": "Korea (the Democratic People's Republic of)", "number": "408"},
  "KOR": { "code3": "KOR", "name": "Korea (the Republic of)", "number": "410"},
  "KWT": { "code3": "KWT", "name": "Kuwait", "number": "414"},
  "KGZ": { "code3": "KGZ", "name": "Kyrgyzstan", "number": "417"},
  "LAO": { "code3": "LAO", "name": "Lao People's Democratic Republic (the)", "number": "418"},
  "LVA": { "code3": "LVA", "name": "Latvia", "number": "428"},
  "LBN": { "code3": "LBN", "name": "Lebanon", "number": "422"},
  "LSO": { "code3": "LSO", "name": "Lesotho", "number": "426"},
  "LBR": { "code3": "LBR", "name": "Liberia", "number": "430"},
  "LBY": { "code3": "LBY", "name": "Libya", "number": "434"},
  "LIE": { "code3": "LIE", "name": "Liechtenstein", "number": "438"},
  "LTU": { "code3": "LTU", "name": "Lithuania", "number": "440"},
  "LUX": { "code3": "LUX", "name": "Luxembourg", "number": "442"},
  "MAC": { "code3": "MAC", "name": "Macao", "number": "446"},
  "MDG": { "code3": "MDG", "name": "Madagascar", "number": "450"},
  "MWI": { "code3": "MWI", "name": "Malawi", "number": "454"},
  "MYS": { "code3": "MYS", "name": "Malaysia", "number": "458"},
  "MDV": { "code3": "MDV", "name": "Maldives", "number": "462"},
  "MLI": { "code3": "MLI", "name": "Mali", "number": "466"},
  "MLT": { "code3": "MLT", "name": "Malta", "number": "470"},
  "MHL": { "code3": "MHL", "name": "Marshall Islands (the)", "number": "584"},
  "MTQ": { "code3": "MTQ", "name": "Martinique", "number": "474"},
  "MRT": { "code3": "MRT", "name": "Mauritania", "number": "478"},
  "MUS": { "code3": "MUS", "name": "Mauritius", "number": "480"},
  "MYT": { "code3": "MYT", "name": "Mayotte", "number": "175"},
  "MEX": { "code3": "MEX", "name": "Mexico", "number": "484"},
  "FSM": { "code3": "FSM", "name": "Micronesia (Federated States of)", "number": "583"},
  "MDA": { "code3": "MDA", "name": "Moldova (the Republic of)", "number": "498"},
  "MCO": { "code3": "MCO", "name": "Monaco", "number": "492"},
  "MNG": { "code3": "MNG", "name": "Mongolia", "number": "496"},
  "MNE": { "code3": "MNE", "name": "Montenegro", "number": "499"},
  "MSR": { "code3": "MSR", "name": "Montserrat", "number": "500"},
  "MAR": { "code3": "MAR", "name": "Morocco", "number": "504"},
  "MOZ": { "code3": "MOZ", "name": "Mozambique", "number": "508"},
  "MMR": { "code3": "MMR", "name": "Myanmar", "number": "104"},
  "NAM": { "code3": "NAM", "name": "Namibia", "number": "516"},
  "NRU": { "code3": "NRU", "name": "Nauru", "number": "520"},
  "NPL": { "code3": "NPL", "name": "Nepal", "number": "524"},
  "NLD": { "code3": "NLD", "name": "Netherlands (the)", "number": "528"},
  "NCL": { "code3": "NCL", "name": "New Caledonia", "number": "540"},
  "NZL": { "code3": "NZL", "name": "New Zealand", "number": "554"},
  "NIC": { "code3": "NIC", "name": "Nicaragua", "number": "558"},
  "NER": { "code3": "NER", "name": "Niger (the)", "number": "562"},
  "NGA": { "code3": "NGA", "name": "Nigeria", "number": "566"},
  "NIU": { "code3": "NIU", "name": "Niue", "number": "570"},
  "NFK": { "code3": "NFK", "name": "Norfolk Island", "number": "574"},
  "MNP": { "code3": "MNP", "name": "Northern Mariana Islands (the)", "number": "580"},
  "NOR": { "code3": "NOR", "name": "Norway", "number": "578"},
  "OMN": { "code3": "OMN", "name": "Oman", "number": "512"},
  "PAK": { "code3": "PAK", "name": "Pakistan", "number": "586"},
  "PLW": { "code3": "PLW", "name": "Palau", "number": "585"},
  "PSE": { "code3": "PSE", "name": "Palestine, State of", "number": "275"},
  "PAN": { "code3": "PAN", "name": "Panama", "number": "591"},
  "PNG": { "code3": "PNG", "name": "Papua New Guinea", "number": "598"},
  "PRY": { "code3": "PRY", "name": "Paraguay", "number": "600"},
  "PER": { "code3": "PER", "name": "Peru", "number": "604"},
  "PHL": { "code3": "PHL", "name": "Philippines (the)", "number": "608"},
  "PCN": { "code3": "PCN", "name": "Pitcairn", "number": "612"},
  "POL": { "code3": "POL", "name": "Poland", "number": "616"},
  "PRT": { "code3": "PRT", "name": "Portugal", "number": "620"},
  "PRI": { "code3": "PRI", "name": "Puerto Rico", "number": "630"},
  "QAT": { "code3": "QAT", "name": "Qatar", "number": "634"},
  "MKD": { "code3": "MKD", "name": "Republic of North Macedonia", "number": "807"},
  "ROU": { "code3": "ROU", "name": "Romania", "number": "642"},
  "RUS": { "code3": "RUS", "name": "Russian Federation (the)", "number": "643"},
  "RWA": { "code3": "RWA", "name": "Rwanda", "number": "646"},
  "REU": { "code3": "REU", "name": "Réunion", "number": "638"},
  "BLM": { "code3": "BLM", "name": "Saint Barthélemy", "number": "652"},
  "SHN": { "code3": "SHN", "name": "Saint Helena, Ascension and Tristan da Cunha", "number": "654"},
  "KNA": { "code3": "KNA", "name": "Saint Kitts and Nevis", "number": "659"},
  "LCA": { "code3": "LCA", "name": "Saint Lucia", "number": "662"},
  "MAF": { "code3": "MAF", "name": "Saint Martin (French part)", "number": "663"},
  "SPM": { "code3": "SPM", "name": "Saint Pierre and Miquelon", "number": "666"},
  "VCT": { "code3": "VCT", "name": "Saint Vincent and the Grenadines", "number": "670"},
  "WSM": { "code3": "WSM", "name": "Samoa", "number": "882"},
  "SMR": { "code3": "SMR", "name": "San Marino", "number": "674"},
  "STP": { "code3": "STP", "name": "Sao Tome and Principe", "number": "678"},
  "SAU": { "code3": "SAU", "name": "Saudi Arabia", "number": "682"},
  "SEN": { "code3": "SEN", "name": "Senegal", "number": "686"},
  "SRB": { "code3": "SRB", "name": "Serbia", "number": "688"},
  "SYC": { "code3": "SYC", "name": "Seychelles", "number": "690"},
  "SLE": { "code3": "SLE", "name": "Sierra Leone", "number": "694"},
  "SGP": { "code3": "SGP", "name": "Singapore", "number": "702"},
  "SXM": { "code3": "SXM", "name": "Sint Maarten (Dutch part)", "number": "534"},
  "SVK": { "code3": "SVK", "name": "Slovakia", "number": "703"},
  "SVN": { "code3": "SVN", "name": "Slovenia", "number": "705"},
  "SLB": { "code3": "SLB", "name": "Solomon Islands", "number": "090"},
  "SOM": { "code3": "SOM", "name": "Somalia", "number": "706"},
  "ZAF": { "code3": "ZAF", "name": "South Africa", "number": "710"},
  "SGS": { "code3": "SGS", "name": "South Georgia and the South Sandwich Islands", "number": "239"},
  "SSD": { "code3": "SSD", "name": "South Sudan", "number": "728"},
  "ESP": { "code3": "ESP", "name": "Spain", "number": "724"},
  "LKA": { "code3": "LKA", "name": "Sri Lanka", "number": "144"},
  "SDN": { "code3": "SDN", "name": "Sudan (the)", "number": "729"},
  "SUR": { "code3": "SUR", "name": "Suriname", "number": "740"},
  "SJM": { "code3": "SJM", "name": "Svalbard and Jan Mayen", "number": "744"},
  "SWE": { "code3": "SWE", "name": "Sweden", "number": "752"},
  "CHE": { "code3": "CHE", "name": "Switzerland", "number": "756"},
  "SYR": { "code3": "SYR", "name": "Syrian Arab Republic", "number": "760"},
  "TWN": { "code3": "TWN", "name": "Taiwan (Province of China)", "number": "158"},
  "TJK": { "code3": "TJK", "name": "Tajikistan", "number": "762"},
  "TZA": { "code3": "TZA", "name": "Tanzania, United Republic of", "number": "834"},
  "THA": { "code3": "THA", "name": "Thailand", "number": "764"},
  "TLS": { "code3": "TLS", "name": "Timor-Leste", "number": "626"},
  "TGO": { "code3": "TGO", "name": "Togo", "number": "768"},
  "TKL": { "code3": "TKL", "name": "Tokelau", "number": "772"},
  "TON": { "code3": "TON", "name": "Tonga", "number": "776"},
  "TTO": { "code3": "TTO", "name": "Trinidad and Tobago", "number": "780"},
  "TUN": { "code3": "TUN", "name": "Tunisia", "number": "788"},
  "TUR": { "code3": "TUR", "name": "Turkey", "number": "792"},
  "TKM": { "code3": "TKM", "name": "Turkmenistan", "number": "795"},
  "TCA": { "code3": "TCA", "name": "Turks and Caicos Islands (the)", "number": "796"},
  "TUV": { "code3": "TUV", "name": "Tuvalu", "number": "798"},
  "UGA": { "code3": "UGA", "name": "Uganda", "number": "800"},
  "UKR": { "code3": "UKR", "name": "Ukraine", "number": "804"},
  "ARE": { "code3": "ARE", "name": "United Arab Emirates (the)", "number": "784"},
  "GBR": { "code3": "GBR", "name": "United Kingdom of Great Britain and Northern Ireland (the)", "number": "826"},
  "UMI": { "code3": "UMI", "name": "United States Minor Outlying Islands (the)", "number": "581"},
  "USA": { "code3": "USA", "name": "United States of America (the)", "number": "840"},
  "URY": { "code3": "URY", "name": "Uruguay", "number": "858"},
  "UZB": { "code3": "UZB", "name": "Uzbekistan", "number": "860"},
  "VUT": { "code3": "VUT", "name": "Vanuatu", "number": "548"},
  "VEN": { "code3": "VEN", "name": "Venezuela (Bolivarian Republic of)", "number": "862"},
  "VNM": { "code3": "VNM", "name": "Viet Nam", "number": "704"},
  "VGB": { "code3": "VGB", "name": "Virgin Islands (British)", "number": "092"},
  "VIR": { "code3": "VIR", "name": "Virgin Islands (U.S.)", "number": "850"},
  "WLF": { "code3": "WLF", "name": "Wallis and Futuna", "number": "876"},
  "ESH": { "code3": "ESH", "name": "Western Sahara", "number": "732"},
  "YEM": { "code3": "YEM", "name": "Yemen", "number": "887"},
  "ZMB": { "code3": "ZMB", "name": "Zambia", "number": "894"},
  "ZWE": { "code3": "ZWE", "name": "Zimbabwe", "number": "716"},
  "ALA": { "code3": "ALA", "name": "Åland Islands", "number": "248"}
};

export const HandEnum = {
  'L': 'Left',
  'R': 'Right'
};

export const SexEnum = {
  0: 'Male',
  1: 'Female'
};

export const ProfyStatus = {
  0: 'WTA',
  1: 'ATP',
  2: 'Other'
};


export const CountrySelectList = {
  "AFG": "Afghanistan",
  "ALB": "Albania",
  "DZA": "Algeria",
  "ASM": "American Samoa",
  "AND": "Andorra",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "ATA": "Antarctica",
  "ATG": "Antigua and Barbuda",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "ABW": "Aruba",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BHS": "Bahamas (the)",
  "BHR": "Bahrain",
  "BGD": "Bangladesh",
  "BRB": "Barbados",
  "BLR": "Belarus",
  "BEL": "Belgium",
  "BLZ": "Belize",
  "BEN": "Benin",
  "BMU": "Bermuda",
  "BTN": "Bhutan",
  "BOL": "Bolivia (Plurinational State of)",
  "BES": "Bonaire, Sint Eustatius and Saba",
  "BIH": "Bosnia and Herzegovina",
  "BWA": "Botswana",
  "BVT": "Bouvet Island",
  "BRA": "Brazil",
  "IOT": "British Indian Ocean Territory (the)",
  "BRN": "Brunei Darussalam",
  "BGR": "Bulgaria",
  "BFA": "Burkina Faso",
  "BDI": "Burundi",
  "CPV": "Cabo Verde",
  "KHM": "Cambodia",
  "CMR": "Cameroon",
  "CAN": "Canada",
  "CYM": "Cayman Islands (the)",
  "CAF": "Central African Republic (the)",
  "TCD": "Chad",
  "CHL": "Chile",
  "CHN": "China",
  "CXR": "Christmas Island",
  "CCK": "Cocos (Keeling) Islands (the)",
  "COL": "Colombia",
  "COM": "Comoros (the)",
  "COD": "Congo (the Democratic Republic of the)",
  "COG": "Congo (the)",
  "COK": "Cook Islands (the)",
  "CRI": "Costa Rica",
  "HRV": "Croatia",
  "CUB": "Cuba",
  "CUW": "Curaçao",
  "CYP": "Cyprus",
  "CZE": "Czechia",
  "CIV": "Côte d'Ivoire",
  "DNK": "Denmark",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DOM": "Dominican Republic (the)",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "SLV": "El Salvador",
  "GNQ": "Equatorial Guinea",
  "ERI": "Eritrea",
  "EST": "Estonia",
  "SWZ": "Eswatini",
  "ETH": "Ethiopia",
  "FLK": "Falkland Islands (the) [Malvinas]",
  "FRO": "Faroe Islands (the)",
  "FJI": "Fiji",
  "FIN": "Finland",
  "FRA": "France",
  "GUF": "French Guiana",
  "PYF": "French Polynesia",
  "ATF": "French Southern Territories (the)",
  "GAB": "Gabon",
  "GMB": "Gambia (the)",
  "GEO": "Georgia",
  "DEU": "Germany",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GRC": "Greece",
  "GRL": "Greenland",
  "GRD": "Grenada",
  "GLP": "Guadeloupe",
  "GUM": "Guam",
  "GTM": "Guatemala",
  "GGY": "Guernsey",
  "GIN": "Guinea",
  "GNB": "Guinea-Bissau",
  "GUY": "Guyana",
  "HTI": "Haiti",
  "HMD": "Heard Island and McDonald Islands",
  "VAT": "Holy See (the)",
  "HND": "Honduras",
  "HKG": "Hong Kong",
  "HUN": "Hungary",
  "ISL": "Iceland",
  "IND": "India",
  "IDN": "Indonesia",
  "IRN": "Iran (Islamic Republic of)",
  "IRQ": "Iraq",
  "IRL": "Ireland",
  "IMN": "Isle of Man",
  "ISR": "Israel",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JPN": "Japan",
  "JEY": "Jersey",
  "JOR": "Jordan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KIR": "Kiribati",
  "PRK": "Korea (the Democratic People's Republic of)",
  "KOR": "Korea (the Republic of)",
  "KWT": "Kuwait",
  "KGZ": "Kyrgyzstan",
  "LAO": "Lao People's Democratic Republic (the)",
  "LVA": "Latvia",
  "LBN": "Lebanon",
  "LSO": "Lesotho",
  "LBR": "Liberia",
  "LBY": "Libya",
  "LIE": "Liechtenstein",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "MAC": "Macao",
  "MDG": "Madagascar",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "MDV": "Maldives",
  "MLI": "Mali",
  "MLT": "Malta",
  "MHL": "Marshall Islands (the)",
  "MTQ": "Martinique",
  "MRT": "Mauritania",
  "MUS": "Mauritius",
  "MYT": "Mayotte",
  "MEX": "Mexico",
  "FSM": "Micronesia (Federated States of)",
  "MDA": "Moldova (the Republic of)",
  "MCO": "Monaco",
  "MNG": "Mongolia",
  "MNE": "Montenegro",
  "MSR": "Montserrat",
  "MAR": "Morocco",
  "MOZ": "Mozambique",
  "MMR": "Myanmar",
  "NAM": "Namibia",
  "NRU": "Nauru",
  "NPL": "Nepal",
  "NLD": "Netherlands (the)",
  "NCL": "New Caledonia",
  "NZL": "New Zealand",
  "NIC": "Nicaragua",
  "NER": "Niger (the)",
  "NGA": "Nigeria",
  "NIU": "Niue",
  "NFK": "Norfolk Island",
  "MNP": "Northern Mariana Islands (the)",
  "NOR": "Norway",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PLW": "Palau",
  "PSE": "Palestine, State of",
  "PAN": "Panama",
  "PNG": "Papua New Guinea",
  "PRY": "Paraguay",
  "PER": "Peru",
  "PHL": "Philippines (the)",
  "PCN": "Pitcairn",
  "POL": "Poland",
  "PRT": "Portugal",
  "PRI": "Puerto Rico",
  "QAT": "Qatar",
  "MKD": "Republic of North Macedonia",
  "ROU": "Romania",
  "RUS": "Russian Federation (the)",
  "RWA": "Rwanda",
  "REU": "Réunion",
  "BLM": "Saint Barthélemy",
  "SHN": "Saint Helena, Ascension and Tristan da Cunha",
  "KNA": "Saint Kitts and Nevis",
  "LCA": "Saint Lucia",
  "MAF": "Saint Martin (French part)",
  "SPM": "Saint Pierre and Miquelon",
  "VCT": "Saint Vincent and the Grenadines",
  "WSM": "Samoa",
  "SMR": "San Marino",
  "STP": "Sao Tome and Principe",
  "SAU": "Saudi Arabia",
  "SEN": "Senegal",
  "SRB": "Serbia",
  "SYC": "Seychelles",
  "SLE": "Sierra Leone",
  "SGP": "Singapore",
  "SXM": "Sint Maarten (Dutch part)",
  "SVK": "Slovakia",
  "SVN": "Slovenia",
  "SLB": "Solomon Islands",
  "SOM": "Somalia",
  "ZAF": "South Africa",
  "SGS": "South Georgia and the South Sandwich Islands",
  "SSD": "South Sudan",
  "ESP": "Spain",
  "LKA": "Sri Lanka",
  "SDN": "Sudan (the)",
  "SUR": "Suriname",
  "SJM": "Svalbard and Jan Mayen",
  "SWE": "Sweden",
  "CHE": "Switzerland",
  "SYR": "Syrian Arab Republic",
  "TWN": "Taiwan (Province of China)",
  "TJK": "Tajikistan",
  "TZA": "Tanzania, United Republic of",
  "THA": "Thailand",
  "TLS": "Timor-Leste",
  "TGO": "Togo",
  "TKL": "Tokelau",
  "TON": "Tonga",
  "TTO": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TUR": "Turkey",
  "TKM": "Turkmenistan",
  "TCA": "Turks and Caicos Islands (the)",
  "TUV": "Tuvalu",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "ARE": "United Arab Emirates (the)",
  "GBR": "United Kingdom of Great Britain and Northern Ireland (the)",
  "UMI": "United States Minor Outlying Islands (the)",
  "USA": "United States of America (the)",
  "URY": "Uruguay",
  "UZB": "Uzbekistan",
  "VUT": "Vanuatu",
  "VEN": "Venezuela (Bolivarian Republic of)",
  "VNM": "Viet Nam",
  "VGB": "Virgin Islands (British)",
  "VIR": "Virgin Islands (U.S.)",
  "WLF": "Wallis and Futuna",
  "ESH": "Western Sahara",
  "YEM": "Yemen",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe",
  "ALA": "Åland Islands"
}

export const TourneyLevels = {
  'A': 'A',
  'B': 'B',
  'C': 'C',
  'D': 'D',
  'E': 'E',
  'F': 'F',
  'G': 'G',
  'H': 'H',
}

export const PlayerEnum = {
  0: 'Player 1',
  1: 'Player 2'
}

export const SurfaceEnum = {
  'Hard': 'Hard',
  'Clay': 'Clay',
  'Carpet': 'Carpet',
  'Grass': 'Grass',
}

export const InjuryEnum = {
  0: 'Stress Fracture',
  1: 'Tennis Elbow',
  2: 'Back Injury',
  3: 'Knee Injury',
  4: 'Psychological Trauma',
}

export const InjuryCoefEnum = {
  0: 0.5,
  1: 0.3,
  2: 0.1,
  3: 0.08,
  4: 0.02,
}
