export const countryList = {
  "AF": { "code3": "AFG", "name": "Afghanistan", "number": "004"},
  "AL": { "code3": "ALB", "name": "Albania", "number": "008"},
  "DZ": { "code3": "DZA", "name": "Algeria", "number": "012"},
  "AS": { "code3": "ASM", "name": "American Samoa", "number": "016"},
  "AD": { "code3": "AND", "name": "Andorra", "number": "020"},
  "AO": { "code3": "AGO", "name": "Angola", "number": "024"},
  "AI": { "code3": "AIA", "name": "Anguilla", "number": "660"},
  "AQ": { "code3": "ATA", "name": "Antarctica", "number": "010"},
  "AG": { "code3": "ATG", "name": "Antigua and Barbuda", "number": "028"},
  "AR": { "code3": "ARG", "name": "Argentina", "number": "032"},
  "AM": { "code3": "ARM", "name": "Armenia", "number": "051"},
  "AW": { "code3": "ABW", "name": "Aruba", "number": "533"},
  "AU": { "code3": "AUS", "name": "Australia", "number": "036"},
  "AT": { "code3": "AUT", "name": "Austria", "number": "040"},
  "AZ": { "code3": "AZE", "name": "Azerbaijan", "number": "031"},
  "BS": { "code3": "BHS", "name": "Bahamas (the)", "number": "044"},
  "BH": { "code3": "BHR", "name": "Bahrain", "number": "048"},
  "BD": { "code3": "BGD", "name": "Bangladesh", "number": "050"},
  "BB": { "code3": "BRB", "name": "Barbados", "number": "052"},
  "BY": { "code3": "BLR", "name": "Belarus", "number": "112"},
  "BE": { "code3": "BEL", "name": "Belgium", "number": "056"},
  "BZ": { "code3": "BLZ", "name": "Belize", "number": "084"},
  "BJ": { "code3": "BEN", "name": "Benin", "number": "204"},
  "BM": { "code3": "BMU", "name": "Bermuda", "number": "060"},
  "BT": { "code3": "BTN", "name": "Bhutan", "number": "064"},
  "BO": { "code3": "BOL", "name": "Bolivia (Plurinational State of)", "number": "068"},
  "BQ": { "code3": "BES", "name": "Bonaire, Sint Eustatius and Saba", "number": "535"},
  "BA": { "code3": "BIH", "name": "Bosnia and Herzegovina", "number": "070"},
  "BW": { "code3": "BWA", "name": "Botswana", "number": "072"},
  "BV": { "code3": "BVT", "name": "Bouvet Island", "number": "074"},
  "BR": { "code3": "BRA", "name": "Brazil", "number": "076"},
  "IO": { "code3": "IOT", "name": "British Indian Ocean Territory (the)", "number": "086"},
  "BN": { "code3": "BRN", "name": "Brunei Darussalam", "number": "096"},
  "BG": { "code3": "BGR", "name": "Bulgaria", "number": "100"},
  "BF": { "code3": "BFA", "name": "Burkina Faso", "number": "854"},
  "BI": { "code3": "BDI", "name": "Burundi", "number": "108"},
  "CV": { "code3": "CPV", "name": "Cabo Verde", "number": "132"},
  "KH": { "code3": "KHM", "name": "Cambodia", "number": "116"},
  "CM": { "code3": "CMR", "name": "Cameroon", "number": "120"},
  "CA": { "code3": "CAN", "name": "Canada", "number": "124"},
  "KY": { "code3": "CYM", "name": "Cayman Islands (the)", "number": "136"},
  "CF": { "code3": "CAF", "name": "Central African Republic (the)", "number": "140"},
  "TD": { "code3": "TCD", "name": "Chad", "number": "148"},
  "CL": { "code3": "CHL", "name": "Chile", "number": "152"},
  "CN": { "code3": "CHN", "name": "China", "number": "156"},
  "CX": { "code3": "CXR", "name": "Christmas Island", "number": "162"},
  "CC": { "code3": "CCK", "name": "Cocos (Keeling) Islands (the)", "number": "166"},
  "CO": { "code3": "COL", "name": "Colombia", "number": "170"},
  "KM": { "code3": "COM", "name": "Comoros (the)", "number": "174"},
  "CD": { "code3": "COD", "name": "Congo (the Democratic Republic of the)", "number": "180"},
  "CG": { "code3": "COG", "name": "Congo (the)", "number": "178"},
  "CK": { "code3": "COK", "name": "Cook Islands (the)", "number": "184"},
  "CR": { "code3": "CRI", "name": "Costa Rica", "number": "188"},
  "HR": { "code3": "HRV", "name": "Croatia", "number": "191"},
  "CU": { "code3": "CUB", "name": "Cuba", "number": "192"},
  "CW": { "code3": "CUW", "name": "Curaçao", "number": "531"},
  "CY": { "code3": "CYP", "name": "Cyprus", "number": "196"},
  "CZ": { "code3": "CZE", "name": "Czechia", "number": "203"},
  "CI": { "code3": "CIV", "name": "Côte d'Ivoire", "number": "384"},
  "DK": { "code3": "DNK", "name": "Denmark", "number": "208"},
  "DJ": { "code3": "DJI", "name": "Djibouti", "number": "262"},
  "DM": { "code3": "DMA", "name": "Dominica", "number": "212"},
  "DO": { "code3": "DOM", "name": "Dominican Republic (the)", "number": "214"},
  "EC": { "code3": "ECU", "name": "Ecuador", "number": "218"},
  "EG": { "code3": "EGY", "name": "Egypt", "number": "818"},
  "SV": { "code3": "SLV", "name": "El Salvador", "number": "222"},
  "GQ": { "code3": "GNQ", "name": "Equatorial Guinea", "number": "226"},
  "ER": { "code3": "ERI", "name": "Eritrea", "number": "232"},
  "EE": { "code3": "EST", "name": "Estonia", "number": "233"},
  "SZ": { "code3": "SWZ", "name": "Eswatini", "number": "748"},
  "ET": { "code3": "ETH", "name": "Ethiopia", "number": "231"},
  "FK": { "code3": "FLK", "name": "Falkland Islands (the) [Malvinas]", "number": "238"},
  "FO": { "code3": "FRO", "name": "Faroe Islands (the)", "number": "234"},
  "FJ": { "code3": "FJI", "name": "Fiji", "number": "242"},
  "FI": { "code3": "FIN", "name": "Finland", "number": "246"},
  "FR": { "code3": "FRA", "name": "France", "number": "250"},
  "GF": { "code3": "GUF", "name": "French Guiana", "number": "254"},
  "PF": { "code3": "PYF", "name": "French Polynesia", "number": "258"},
  "TF": { "code3": "ATF", "name": "French Southern Territories (the)", "number": "260"},
  "GA": { "code3": "GAB", "name": "Gabon", "number": "266"},
  "GM": { "code3": "GMB", "name": "Gambia (the)", "number": "270"},
  "GE": { "code3": "GEO", "name": "Georgia", "number": "268"},
  "DE": { "code3": "DEU", "name": "Germany", "number": "276"},
  "GH": { "code3": "GHA", "name": "Ghana", "number": "288"},
  "GI": { "code3": "GIB", "name": "Gibraltar", "number": "292"},
  "GR": { "code3": "GRC", "name": "Greece", "number": "300"},
  "GL": { "code3": "GRL", "name": "Greenland", "number": "304"},
  "GD": { "code3": "GRD", "name": "Grenada", "number": "308"},
  "GP": { "code3": "GLP", "name": "Guadeloupe", "number": "312"},
  "GU": { "code3": "GUM", "name": "Guam", "number": "316"},
  "GT": { "code3": "GTM", "name": "Guatemala", "number": "320"},
  "GG": { "code3": "GGY", "name": "Guernsey", "number": "831"},
  "GN": { "code3": "GIN", "name": "Guinea", "number": "324"},
  "GW": { "code3": "GNB", "name": "Guinea-Bissau", "number": "624"},
  "GY": { "code3": "GUY", "name": "Guyana", "number": "328"},
  "HT": { "code3": "HTI", "name": "Haiti", "number": "332"},
  "HM": { "code3": "HMD", "name": "Heard Island and McDonald Islands", "number": "334"},
  "VA": { "code3": "VAT", "name": "Holy See (the)", "number": "336"},
  "HN": { "code3": "HND", "name": "Honduras", "number": "340"},
  "HK": { "code3": "HKG", "name": "Hong Kong", "number": "344"},
  "HU": { "code3": "HUN", "name": "Hungary", "number": "348"},
  "IS": { "code3": "ISL", "name": "Iceland", "number": "352"},
  "IN": { "code3": "IND", "name": "India", "number": "356"},
  "ID": { "code3": "IDN", "name": "Indonesia", "number": "360"},
  "IR": { "code3": "IRN", "name": "Iran (Islamic Republic of)", "number": "364"},
  "IQ": { "code3": "IRQ", "name": "Iraq", "number": "368"},
  "IE": { "code3": "IRL", "name": "Ireland", "number": "372"},
  "IM": { "code3": "IMN", "name": "Isle of Man", "number": "833"},
  "IL": { "code3": "ISR", "name": "Israel", "number": "376"},
  "IT": { "code3": "ITA", "name": "Italy", "number": "380"},
  "JM": { "code3": "JAM", "name": "Jamaica", "number": "388"},
  "JP": { "code3": "JPN", "name": "Japan", "number": "392"},
  "JE": { "code3": "JEY", "name": "Jersey", "number": "832"},
  "JO": { "code3": "JOR", "name": "Jordan", "number": "400"},
  "KZ": { "code3": "KAZ", "name": "Kazakhstan", "number": "398"},
  "KE": { "code3": "KEN", "name": "Kenya", "number": "404"},
  "KI": { "code3": "KIR", "name": "Kiribati", "number": "296"},
  "KP": { "code3": "PRK", "name": "Korea (the Democratic People's Republic of)", "number": "408"},
  "KR": { "code3": "KOR", "name": "Korea (the Republic of)", "number": "410"},
  "KW": { "code3": "KWT", "name": "Kuwait", "number": "414"},
  "KG": { "code3": "KGZ", "name": "Kyrgyzstan", "number": "417"},
  "LA": { "code3": "LAO", "name": "Lao People's Democratic Republic (the)", "number": "418"},
  "LV": { "code3": "LVA", "name": "Latvia", "number": "428"},
  "LB": { "code3": "LBN", "name": "Lebanon", "number": "422"},
  "LS": { "code3": "LSO", "name": "Lesotho", "number": "426"},
  "LR": { "code3": "LBR", "name": "Liberia", "number": "430"},
  "LY": { "code3": "LBY", "name": "Libya", "number": "434"},
  "LI": { "code3": "LIE", "name": "Liechtenstein", "number": "438"},
  "LT": { "code3": "LTU", "name": "Lithuania", "number": "440"},
  "LU": { "code3": "LUX", "name": "Luxembourg", "number": "442"},
  "MO": { "code3": "MAC", "name": "Macao", "number": "446"},
  "MG": { "code3": "MDG", "name": "Madagascar", "number": "450"},
  "MW": { "code3": "MWI", "name": "Malawi", "number": "454"},
  "MY": { "code3": "MYS", "name": "Malaysia", "number": "458"},
  "MV": { "code3": "MDV", "name": "Maldives", "number": "462"},
  "ML": { "code3": "MLI", "name": "Mali", "number": "466"},
  "MT": { "code3": "MLT", "name": "Malta", "number": "470"},
  "MH": { "code3": "MHL", "name": "Marshall Islands (the)", "number": "584"},
  "MQ": { "code3": "MTQ", "name": "Martinique", "number": "474"},
  "MR": { "code3": "MRT", "name": "Mauritania", "number": "478"},
  "MU": { "code3": "MUS", "name": "Mauritius", "number": "480"},
  "YT": { "code3": "MYT", "name": "Mayotte", "number": "175"},
  "MX": { "code3": "MEX", "name": "Mexico", "number": "484"},
  "FM": { "code3": "FSM", "name": "Micronesia (Federated States of)", "number": "583"},
  "MD": { "code3": "MDA", "name": "Moldova (the Republic of)", "number": "498"},
  "MC": { "code3": "MCO", "name": "Monaco", "number": "492"},
  "MN": { "code3": "MNG", "name": "Mongolia", "number": "496"},
  "ME": { "code3": "MNE", "name": "Montenegro", "number": "499"},
  "MS": { "code3": "MSR", "name": "Montserrat", "number": "500"},
  "MA": { "code3": "MAR", "name": "Morocco", "number": "504"},
  "MZ": { "code3": "MOZ", "name": "Mozambique", "number": "508"},
  "MM": { "code3": "MMR", "name": "Myanmar", "number": "104"},
  "NA": { "code3": "NAM", "name": "Namibia", "number": "516"},
  "NR": { "code3": "NRU", "name": "Nauru", "number": "520"},
  "NP": { "code3": "NPL", "name": "Nepal", "number": "524"},
  "NL": { "code3": "NLD", "name": "Netherlands (the)", "number": "528"},
  "NC": { "code3": "NCL", "name": "New Caledonia", "number": "540"},
  "NZ": { "code3": "NZL", "name": "New Zealand", "number": "554"},
  "NI": { "code3": "NIC", "name": "Nicaragua", "number": "558"},
  "NE": { "code3": "NER", "name": "Niger (the)", "number": "562"},
  "NG": { "code3": "NGA", "name": "Nigeria", "number": "566"},
  "NU": { "code3": "NIU", "name": "Niue", "number": "570"},
  "NF": { "code3": "NFK", "name": "Norfolk Island", "number": "574"},
  "MP": { "code3": "MNP", "name": "Northern Mariana Islands (the)", "number": "580"},
  "NO": { "code3": "NOR", "name": "Norway", "number": "578"},
  "OM": { "code3": "OMN", "name": "Oman", "number": "512"},
  "PK": { "code3": "PAK", "name": "Pakistan", "number": "586"},
  "PW": { "code3": "PLW", "name": "Palau", "number": "585"},
  "PS": { "code3": "PSE", "name": "Palestine, State of", "number": "275"},
  "PA": { "code3": "PAN", "name": "Panama", "number": "591"},
  "PG": { "code3": "PNG", "name": "Papua New Guinea", "number": "598"},
  "PY": { "code3": "PRY", "name": "Paraguay", "number": "600"},
  "PE": { "code3": "PER", "name": "Peru", "number": "604"},
  "PH": { "code3": "PHL", "name": "Philippines (the)", "number": "608"},
  "PN": { "code3": "PCN", "name": "Pitcairn", "number": "612"},
  "PL": { "code3": "POL", "name": "Poland", "number": "616"},
  "PT": { "code3": "PRT", "name": "Portugal", "number": "620"},
  "PR": { "code3": "PRI", "name": "Puerto Rico", "number": "630"},
  "QA": { "code3": "QAT", "name": "Qatar", "number": "634"},
  "MK": { "code3": "MKD", "name": "Republic of North Macedonia", "number": "807"},
  "RO": { "code3": "ROU", "name": "Romania", "number": "642"},
  "RU": { "code3": "RUS", "name": "Russian Federation (the)", "number": "643"},
  "RW": { "code3": "RWA", "name": "Rwanda", "number": "646"},
  "RE": { "code3": "REU", "name": "Réunion", "number": "638"},
  "BL": { "code3": "BLM", "name": "Saint Barthélemy", "number": "652"},
  "SH": { "code3": "SHN", "name": "Saint Helena, Ascension and Tristan da Cunha", "number": "654"},
  "KN": { "code3": "KNA", "name": "Saint Kitts and Nevis", "number": "659"},
  "LC": { "code3": "LCA", "name": "Saint Lucia", "number": "662"},
  "MF": { "code3": "MAF", "name": "Saint Martin (French part)", "number": "663"},
  "PM": { "code3": "SPM", "name": "Saint Pierre and Miquelon", "number": "666"},
  "VC": { "code3": "VCT", "name": "Saint Vincent and the Grenadines", "number": "670"},
  "WS": { "code3": "WSM", "name": "Samoa", "number": "882"},
  "SM": { "code3": "SMR", "name": "San Marino", "number": "674"},
  "ST": { "code3": "STP", "name": "Sao Tome and Principe", "number": "678"},
  "SA": { "code3": "SAU", "name": "Saudi Arabia", "number": "682"},
  "SN": { "code3": "SEN", "name": "Senegal", "number": "686"},
  "RS": { "code3": "SRB", "name": "Serbia", "number": "688"},
  "SC": { "code3": "SYC", "name": "Seychelles", "number": "690"},
  "SL": { "code3": "SLE", "name": "Sierra Leone", "number": "694"},
  "SG": { "code3": "SGP", "name": "Singapore", "number": "702"},
  "SX": { "code3": "SXM", "name": "Sint Maarten (Dutch part)", "number": "534"},
  "SK": { "code3": "SVK", "name": "Slovakia", "number": "703"},
  "SI": { "code3": "SVN", "name": "Slovenia", "number": "705"},
  "SB": { "code3": "SLB", "name": "Solomon Islands", "number": "090"},
  "SO": { "code3": "SOM", "name": "Somalia", "number": "706"},
  "ZA": { "code3": "ZAF", "name": "South Africa", "number": "710"},
  "GS": { "code3": "SGS", "name": "South Georgia and the South Sandwich Islands", "number": "239"},
  "SS": { "code3": "SSD", "name": "South Sudan", "number": "728"},
  "ES": { "code3": "ESP", "name": "Spain", "number": "724"},
  "LK": { "code3": "LKA", "name": "Sri Lanka", "number": "144"},
  "SD": { "code3": "SDN", "name": "Sudan (the)", "number": "729"},
  "SR": { "code3": "SUR", "name": "Suriname", "number": "740"},
  "SJ": { "code3": "SJM", "name": "Svalbard and Jan Mayen", "number": "744"},
  "SE": { "code3": "SWE", "name": "Sweden", "number": "752"},
  "CH": { "code3": "CHE", "name": "Switzerland", "number": "756"},
  "SY": { "code3": "SYR", "name": "Syrian Arab Republic", "number": "760"},
  "TW": { "code3": "TWN", "name": "Taiwan (Province of China)", "number": "158"},
  "TJ": { "code3": "TJK", "name": "Tajikistan", "number": "762"},
  "TZ": { "code3": "TZA", "name": "Tanzania, United Republic of", "number": "834"},
  "TH": { "code3": "THA", "name": "Thailand", "number": "764"},
  "TL": { "code3": "TLS", "name": "Timor-Leste", "number": "626"},
  "TG": { "code3": "TGO", "name": "Togo", "number": "768"},
  "TK": { "code3": "TKL", "name": "Tokelau", "number": "772"},
  "TO": { "code3": "TON", "name": "Tonga", "number": "776"},
  "TT": { "code3": "TTO", "name": "Trinidad and Tobago", "number": "780"},
  "TN": { "code3": "TUN", "name": "Tunisia", "number": "788"},
  "TR": { "code3": "TUR", "name": "Turkey", "number": "792"},
  "TM": { "code3": "TKM", "name": "Turkmenistan", "number": "795"},
  "TC": { "code3": "TCA", "name": "Turks and Caicos Islands (the)", "number": "796"},
  "TV": { "code3": "TUV", "name": "Tuvalu", "number": "798"},
  "UG": { "code3": "UGA", "name": "Uganda", "number": "800"},
  "UA": { "code3": "UKR", "name": "Ukraine", "number": "804"},
  "AE": { "code3": "ARE", "name": "United Arab Emirates (the)", "number": "784"},
  "GB": { "code3": "GBR", "name": "United Kingdom of Great Britain and Northern Ireland (the)", "number": "826"},
  "UM": { "code3": "UMI", "name": "United States Minor Outlying Islands (the)", "number": "581"},
  "US": { "code3": "USA", "name": "United States of America (the)", "number": "840"},
  "UY": { "code3": "URY", "name": "Uruguay", "number": "858"},
  "UZ": { "code3": "UZB", "name": "Uzbekistan", "number": "860"},
  "VU": { "code3": "VUT", "name": "Vanuatu", "number": "548"},
  "VE": { "code3": "VEN", "name": "Venezuela (Bolivarian Republic of)", "number": "862"},
  "VN": { "code3": "VNM", "name": "Viet Nam", "number": "704"},
  "VG": { "code3": "VGB", "name": "Virgin Islands (British)", "number": "092"},
  "VI": { "code3": "VIR", "name": "Virgin Islands (U.S.)", "number": "850"},
  "WF": { "code3": "WLF", "name": "Wallis and Futuna", "number": "876"},
  "EH": { "code3": "ESH", "name": "Western Sahara", "number": "732"},
  "YE": { "code3": "YEM", "name": "Yemen", "number": "887"},
  "ZM": { "code3": "ZMB", "name": "Zambia", "number": "894"},
  "ZW": { "code3": "ZWE", "name": "Zimbabwe", "number": "716"},
  "AX": { "code3": "ALA", "name": "Åland Islands", "number": "248"}
};

export const HandEnum = {
  0: 'Left',
  1: 'Right'
};

export const SexEnum = {
  0: 'Male',
  1: 'Female'
};

export const ProfyStatus = {
  0: 'WTA',
  1: 'ATP',
  2: 'Other'
};


export const CountrySelectList = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas (the)",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia (Plurinational State of)",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory (the)",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cabo Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands (the)",
  "CF": "Central African Republic (the)",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands (the)",
  "CO": "Colombia",
  "KM": "Comoros (the)",
  "CD": "Congo (the Democratic Republic of the)",
  "CG": "Congo (the)",
  "CK": "Cook Islands (the)",
  "CR": "Costa Rica",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "CI": "Côte d'Ivoire",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic (the)",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "SZ": "Eswatini",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (the) [Malvinas]",
  "FO": "Faroe Islands (the)",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories (the)",
  "GA": "Gabon",
  "GM": "Gambia (the)",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VA": "Holy See (the)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran (Islamic Republic of)",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea (the Democratic People's Republic of)",
  "KR": "Korea (the Republic of)",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic (the)",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands (the)",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia (Federated States of)",
  "MD": "Moldova (the Republic of)",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands (the)",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger (the)",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands (the)",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestine, State of",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines (the)",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "MK": "Republic of North Macedonia",
  "RO": "Romania",
  "RU": "Russian Federation (the)",
  "RW": "Rwanda",
  "RE": "Réunion",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin (French part)",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten (Dutch part)",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan (the)",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan (Province of China)",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands (the)",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates (the)",
  "GB": "United Kingdom of Great Britain and Northern Ireland (the)",
  "UM": "United States Minor Outlying Islands (the)",
  "US": "United States of America (the)",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela (Bolivarian Republic of)",
  "VN": "Viet Nam",
  "VG": "Virgin Islands (British)",
  "VI": "Virgin Islands (U.S.)",
  "WF": "Wallis and Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "AX": "Åland Islands"
}
